In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
df = pd.read_csv('synthetic_dataset.csv')
df.head()

Unnamed: 0  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
0           0            7      149             96             19       10   
1           1            0      151             44              6      105   
2           2            3      169             57             24      240   
3           3            4       86             61             35        0   
4           4            6       75             62             31       77   

         BMI  DiabetesPedigreeFunction  Age  Outcome  
0  38.387409                  0.561331   40        1  
1  26.125923                  0.463959   27        1  
2  33.224573                  0.541364   36        0  
3  32.918264                  0.526311   39        0  
4  37.453830                  0.178734   21        0

In [3]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [4]:
X= df.iloc[:,:-1]

In [5]:
y = df['Outcome']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20,random_state=23)

In [7]:
def standardize(column):
    return (column - column.mean()) / column.std()

In [8]:
def apply(X):
    cols=list(X)
    for i in cols:
        X[i]=standardize(X[i])

In [9]:
apply(X_train)
apply(X_test)

In [10]:
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

In [11]:
y_train.size

400

In [12]:
def one_hot(matrix):
    shape = (matrix.size, matrix.max()+1)
    one_hot = np.zeros(shape)
    rows = np.arange(matrix.size)
    one_hot[rows, matrix.ravel()] = 1
    one_hot = one_hot.reshape((*matrix.shape, matrix.max()+1))
    return one_hot

In [13]:
T = one_hot(y_train)

In [14]:
T.shape

(400, 2)

In [15]:
X_train

array([[-0.33457025, -0.91251247, -1.3448039 , ..., -1.10590222,
        -0.64085597, -0.84249634],
       [ 1.59564272, -0.35210077,  0.48255266, ..., -1.15779101,
        -1.4521732 , -1.3240604 ],
       [ 0.63053624, -1.64989628,  0.11708135, ...,  0.12617535,
        -0.52946587, -1.13143478],
       ...,
       [ 0.9522384 , -1.2664567 , -0.19617978, ..., -0.01908171,
        -1.034462  ,  0.1206318 ],
       [-0.65627241,  1.44711573,  1.89222772, ...,  0.28784748,
         0.59447617, -0.36093227],
       [-0.33457025, -1.41393346, -0.87491222, ...,  0.86032553,
         1.56002264, -1.03512196]])

In [16]:
z= np.ones((400,1))

In [17]:
z

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [18]:
Xtil = np.append(z,X_train,axis=1)

In [19]:
Xtil.shape

(400, 9)

In [20]:
w = np.dot((np.linalg.inv(np.dot(Xtil.T,Xtil))),(np.dot(Xtil.T,T)))

In [21]:
w.shape

(9, 2)

In [22]:
X_test.shape

(100, 8)

In [23]:
zt = np.ones((100,1))

In [24]:
X_test_til = np.append(zt, X_test, axis=1)

In [25]:
X_test_til.shape

(100, 9)

In [26]:
X_test_til.shape

(100, 9)

In [27]:
y_pred = np.dot(X_test_til , w)

In [28]:
y_pred.shape

(100, 2)

In [29]:
y_pred

array([[ 0.41844851,  0.58155149],
       [ 0.24864284,  0.75135716],
       [ 0.77800804,  0.22199196],
       [ 0.5698359 ,  0.4301641 ],
       [ 0.79408981,  0.20591019],
       [ 0.79491046,  0.20508954],
       [ 0.77375698,  0.22624302],
       [ 0.30886308,  0.69113692],
       [ 0.93582803,  0.06417197],
       [ 0.82370005,  0.17629995],
       [ 0.62611177,  0.37388823],
       [ 0.97025127,  0.02974873],
       [ 0.7543704 ,  0.2456296 ],
       [ 0.84541022,  0.15458978],
       [ 0.51951699,  0.48048301],
       [ 0.63408079,  0.36591921],
       [ 0.36687673,  0.63312327],
       [ 0.44565773,  0.55434227],
       [ 0.52034382,  0.47965618],
       [ 0.70806917,  0.29193083],
       [ 0.68374228,  0.31625772],
       [ 0.41787974,  0.58212026],
       [ 0.91314751,  0.08685249],
       [ 0.84597564,  0.15402436],
       [ 0.48697992,  0.51302008],
       [ 0.71519256,  0.28480744],
       [ 0.66545306,  0.33454694],
       [ 0.91737058,  0.08262942],
       [ 0.78044545,

In [30]:
y_pred_act = np.argmax(y_pred,axis =1)

In [31]:
y_pred_act

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0], dtype=int64)

In [32]:
def accuracy(y_pred,y_test):
    acc = np.sum(np.equal(y_pred,y_test))/y_pred.size
    return acc

In [33]:
accuracy(y_test,y_pred_act)

0.82